// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// permute_genotypes_C
IntegerVector permute_genotypes_C(double beta, IntegerVector genotypes, NumericVector phenotypes);
RcppExport SEXP _grspwr_permute_genotypes_C(SEXP betaSEXP, SEXP genotypesSEXP, SEXP phenotypesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type genotypes(genotypesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phenotypes(phenotypesSEXP);
    rcpp_result_gen = Rcpp::wrap(permute_genotypes_C(beta, genotypes, phenotypes));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_grspwr_permute_genotypes_C", (DL_FUNC) &_grspwr_permute_genotypes_C, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_grspwr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
